### ISSUE TITLE
How to get the confidence interval?

### ISSUE THREAD

**Issue by Sisi-Wiciel** [pistacliffcho/icenReg_devel#8]
Thanks for your great work.
I am new to analyzing interval-censored data, I am lucky that I can found this package to analyze data easily. But I need your help that I don't know how to get the confidence interval of ic_sp().
Thanks a lot.

**Comment by pistacliffcho** [comment]
Hi Sisi-Wiciel,

The most common method for constructing confidence interval for regression
parameters is to use a standard Wald confidence interval, that is

Estimate +- 1.96 * Standard Error

The estimate and standard error for a regression parameter can be seen from
the summary table (i.e., summary(fitted_model)).

Let me know if that answers your question!

Best,
Cliff

**Comment by Sisi-Wiciel** [comment]
Thank you so much！I have found where I got wrong.
I didn't set the {bs_sample} of ic_sp(), so I couldn't got the Std.Error from the summary() .
It is wonderful!!
I'm so sorry that I got another problem.
How can I got the  Std.Error and p.value by using $ or [].
For example, I can get the estimate by using ` fit$coefficients `or  ` fit[["coefficients"]]`
I have tried my best to solve this problem, but I still don't know how to get the  Std.Error and p.value.
I have to solve this problem because I want to do the subgroup analysis and draw forest plot.
Thanks again.
Best,
Sisi

**Comment by pistacliffcho** [comment]
Hi Sisi-Wiciel,

There are two ways of getting at the standard deviation. The first is the
most common for R packages, and that is to use the cov() function. This
will return the full covariance matrix, so to get the standard errors, just
take the square root of the diagonal of this matrix, i.e.,

all_std_errs = sqrt( diag( cov(fitted_model) ) )

The second way to is query the summary object. If you call summary(fit),
this actually returns an object that is usually printed. Instead of just
printing, you can extract all the values that are printed out. This is a
little tricky, so I've provided some code below to demonstrate.

Best,
Cliff

library(icenReg)
data(miceData)

# fit model
fit = ic_sp(cbind(l,u) ~ grp, data = miceData, bs_samples = 100)

# get summary object.
# Note that this object is more complicated than
# what is shown from summary(fit)
sum_obj = summary(fit)

# get full table that is normally printed
sum_table = sum_obj$summaryParameters

# extracting p-value for "grp" regression estimate
sum_table["grpge", "p"]

# extracting standard error
sum_table["grpge", "Std.Error"]

**Comment by Sisi-Wiciel** [comment]
Waaaa!!!! I got it!!!!!! Thank you so much!!!!
